In [ ]:
! pip install -r requirements.txt

In [1]:
import pandas as pd
import plotly.express as px

%matplotlib inline

In [29]:
target = "data/machines.csv"

In [30]:
df1 = pd.read_csv(target)

In [8]:
df.head()

,setting1,setting2,setting3,s1,s2,s3,s4,s5,s6,s7,...,s13,s14,s15,s16,s17,s18,s19,s20,s21,Category
0,0.833134,0.997625,1.000000e+00,6.026878e-02,0.181576,0.311201,0.273095,1.465921e-01,1.440252e-01,0.138036,...,0.992394,0.476508,0.369948,0.0001,0.322917,6.511628e-01,1.000000e+00,0.156036,0.159082,Heathly
1,0.999767,0.998575,1.000000e+00,1.360000e-08,0.131847,0.296600,0.245535,9.340000e-08,6.290000e-08,0.004081,...,0.992229,0.533013,0.381408,0.0001,0.281250,6.279070e-01,1.000000e+00,0.007888,0.014562,Heathly
2,0.595096,0.738480,2.500000e-08,2.380888e-01,0.016332,0.035297,0.056997,2.931840e-01,2.081762e-01,0.092860,...,0.001157,0.039296,0.936731,0.0001,0.062500,2.110000e-09,6.640000e-08,0.133745,0.151414,Heathly
3,0.999993,0.999525,1.000000e+00,1.360000e-08,0.128269,0.298795,0.246979,9.340000e-08,6.290000e-08,0.003962,...,0.992091,0.524349,0.372401,0.0001,0.270833,6.279070e-01,1.000000e+00,0.014060,0.026144,Heathly
4,0.595137,0.736699,2.500000e-08,2.380888e-01,0.014130,0.037871,0.058152,2.931840e-01,2.088051e-01,0.091284,...,0.001075,0.030633,0.937537,0.0001,0.062500,2.110000e-09,6.640000e-08,0.135460,0.143240,Heathly

In [13]:
df.drop(["Category"], axis = 1, inplace = True)

In [12]:
target = df["Category"].values

In [18]:
X

array([[-1.07191739, -0.61166295,  0.10657466],
       [-1.36495115, -0.71214133,  0.20219544],
       [-1.8221029 ,  1.32637594, -0.72304785],
       ...,
       [ 0.71528602,  0.507152  ,  0.56413064],
       [ 0.65564043,  0.45432694,  0.60662386],
       [ 0.88208985,  0.51323083,  0.44625576]])

In [21]:
pca = pd.DataFrame(X)

In [24]:
pca.columns = ["PC0","PC1", "PC2"]

In [26]:
pca["status"] = target

In [31]:
df1.head()

,Unnamed: 0,source,id,cycle,setting1,setting2,setting3,s1,s2,s3,...,s16,s17,s18,s19,s20,s21,max,RUL,Category,survival
0,0,train2,1,1,0.833134,0.997625,1.000000e+00,6.026878e-02,0.181576,0.311201,...,0.0001,0.322917,6.511628e-01,1.000000e+00,0.156036,0.159082,149,148,Heathly,0.843773
1,1,train2,1,2,0.999767,0.998575,1.000000e+00,1.360000e-08,0.131847,0.296600,...,0.0001,0.281250,6.279070e-01,1.000000e+00,0.007888,0.014562,149,147,Heathly,0.847011
2,2,train2,1,3,0.595096,0.738480,2.500000e-08,2.380888e-01,0.016332,0.035297,...,0.0001,0.062500,2.110000e-09,6.640000e-08,0.133745,0.151414,149,146,Heathly,0.850210
3,3,train2,1,4,0.999993,0.999525,1.000000e+00,1.360000e-08,0.128269,0.298795,...,0.0001,0.270833,6.279070e-01,1.000000e+00,0.014060,0.026144,149,145,Heathly,0.853370
4,4,train2,1,5,0.595137,0.736699,2.500000e-08,2.380888e-01,0.014130,0.037871,...,0.0001,0.062500,2.110000e-09,6.640000e-08,0.135460,0.143240,149,144,Heathly,0.856490

In [32]:
pca["id"] = df1["id"]

In [35]:
pca

             PC0       PC1       PC2    status   id
0      -1.071917 -0.611663  0.106575   Heathly    1
1      -1.364951 -0.712141  0.202195   Heathly    1
2      -1.822103  1.326376 -0.723048   Heathly    1
3      -1.365015 -0.705467  0.203497   Heathly    1
4      -1.822407  1.326548 -0.720761   Heathly    1
...          ...       ...       ...       ...  ...
160354  0.792061  0.525317  0.507672  Critical  100
160355  0.865255  0.584985  0.454612  Critical  100
160356  0.715286  0.507152  0.564131  Critical  100
160357  0.655640  0.454327  0.606624  Critical  100
160358  0.882090  0.513231  0.446256  Critical  100

[160359 rows x 5 columns]

In [46]:
dis = np.sqrt(pca["PC0"]**2 + pca["PC1"]**2 + pca["PC2"]**2)

In [50]:
pca["c"] = pca["PC2"]**2

In [47]:
pca.dtypes

PC0       float64
PC1       float64
PC2       float64
status     object
id          int64
dtype: object

In [54]:
pca["sum"] = pca[["a", "b", "c"]].sum(axis =1)

In [55]:
pca["dist"] = np.sqrt(pca["sum"])

In [58]:
df1.head()

,Unnamed: 0,source,id,cycle,setting1,setting2,setting3,s1,s2,s3,...,s16,s17,s18,s19,s20,s21,max,RUL,Category,survival
0,0,train2,1,1,0.833134,0.997625,1.000000e+00,6.026878e-02,0.181576,0.311201,...,0.0001,0.322917,6.511628e-01,1.000000e+00,0.156036,0.159082,149,148,Heathly,0.843773
1,1,train2,1,2,0.999767,0.998575,1.000000e+00,1.360000e-08,0.131847,0.296600,...,0.0001,0.281250,6.279070e-01,1.000000e+00,0.007888,0.014562,149,147,Heathly,0.847011
2,2,train2,1,3,0.595096,0.738480,2.500000e-08,2.380888e-01,0.016332,0.035297,...,0.0001,0.062500,2.110000e-09,6.640000e-08,0.133745,0.151414,149,146,Heathly,0.850210
3,3,train2,1,4,0.999993,0.999525,1.000000e+00,1.360000e-08,0.128269,0.298795,...,0.0001,0.270833,6.279070e-01,1.000000e+00,0.014060,0.026144,149,145,Heathly,0.853370
4,4,train2,1,5,0.595137,0.736699,2.500000e-08,2.380888e-01,0.014130,0.037871,...,0.0001,0.062500,2.110000e-09,6.640000e-08,0.135460,0.143240,149,144,Heathly,0.856490

In [59]:
df1.columns

Index(['Unnamed: 0', 'source', 'id', 'cycle', 'setting1', 'setting2',
       'setting3', 's1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10',
       's11', 's12', 's13', 's14', 's15', 's16', 's17', 's18', 's19', 's20',
       's21', 'max', 'RUL', 'Category', 'survival'],
      dtype='object')

In [60]:
drop = ['Unnamed: 0', 'source', 'id', 'cycle', 'max', 'RUL', 'Category', 'survival']

In [67]:
df2 = df1[[ 'setting1', 'setting2',
       'setting3', 's1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10',
       's11', 's12', 's13', 's14', 's15', 's16', 's17', 's18', 's19', 's20',
       's21']]

In [68]:
df2

,setting1,setting2,setting3,s1,s2,s3,s4,s5,s6,s7,...,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
0,0.833134,0.997625,1.000000e+00,6.026878e-02,0.181576,0.311201,0.273095,1.465921e-01,1.440252e-01,0.138036,...,0.136817,0.992394,0.476508,0.369948,0.0001,0.322917,6.511628e-01,1.000000e+00,0.156036,0.159082
1,0.999767,0.998575,1.000000e+00,1.360000e-08,0.131847,0.296600,0.245535,9.340000e-08,6.290000e-08,0.004081,...,0.003297,0.992229,0.533013,0.381408,0.0001,0.281250,6.279070e-01,1.000000e+00,0.007888,0.014562
2,0.595096,0.738480,2.500000e-08,2.380888e-01,0.016332,0.035297,0.056997,2.931840e-01,2.081762e-01,0.092860,...,0.089030,0.001157,0.039296,0.936731,0.0001,0.062500,2.110000e-09,6.640000e-08,0.133745,0.151414
3,0.999993,0.999525,1.000000e+00,1.360000e-08,0.128269,0.298795,0.246979,9.340000e-08,6.290000e-08,0.003962,...,0.004058,0.992091,0.524349,0.372401,0.0001,0.270833,6.279070e-01,1.000000e+00,0.014060,0.026144
4,0.595137,0.736699,2.500000e-08,2.380888e-01,0.014130,0.037871,0.058152,2.931840e-01,2.088051e-01,0.091284,...,0.089258,0.001075,0.030633,0.937537,0.0001,0.062500,2.110000e-09,6.640000e-08,0.135460,0.143240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160354,0.477042,0.250624,1.000000e+00,1.000000e+00,0.686747,0.587312,0.782917,1.000000e+00,1.000000e+00,0.254428,...,0.170576,0.558824,0.194344,0.656792,1.0000,0.750000,1.000000e+00,1.000000e+00,0.271318,0.109501
160355,0.408080,0.084097,1.000000e+00,1.000000e+00,0.701807,0.729453,0.866475,1.000000e+00,1.000000e+00,0.162641,...,0.211088,0.500001,0.188668,0.727204,1.0000,0.583333,1.000000e+00,1.000000e+00,0.124032,0.366198
160356,0.523016,0.500416,1.000000e+00,1.000000e+00,0.665663,0.684979,0.775321,1.000000e+00,1.000000e+00,0.175523,...,0.281450,0.529412,0.212148,0.922278,1.0000,0.833333,1.000000e+00,1.000000e+00,0.232559,0.053992
160357,0.436814,0.750208,1.000000e+00,1.000000e+00,0.608434,0.746021,0.747468,1.000000e+00,1.000000e+00,0.133656,...,0.208955,0.514707,0.203065,0.823394,1.0000,0.583333,1.000000e+00,1.000000e+00,0.116280,0.234467
160358,0.316131,0.084097,1.000000e+00,1.000000e+00,0.795181,0.639634,0.842167,1.000000e+00,1.000000e+00,0.151369,...,0.130064,0.558824,0.192951,0.687573,1.0000,0.666667,1.000000e+00,1.000000e+00,0.178295,0.218173

In [69]:
from sklearn import decomposition



pca = decomposition.PCA(n_components=2)
pca.fit(df2)
X = pca.transform(df2)

In [70]:
X

array([[-1.07191739, -0.61166295],
       [-1.36495115, -0.71214133],
       [-1.8221029 ,  1.32637594],
       ...,
       [ 0.71528602,  0.507152  ],
       [ 0.65564043,  0.45432694],
       [ 0.88208985,  0.51323083]])

In [71]:
p = pd.DataFrame(X)

In [ ]:
fig = px.scatter(p, x=0, y=1, color = df1["Category"])
fig.show()

In [ ]:

fig = px.scatter_3d(pca, x="PC0", y="PC1", z="PC2", color = "status", hover_data=["id"])
fig.show()