
### Working with Excel

#### Openpyxl is a library for manipulating Excel workbooks and worksheets. In this example we read in a workbook, navigate to a specific sheet and save the values on that sheet as a Pandas DataFrame. Then we can use Pandas methods to clean the data and save it back to the same workbook in a new worksheet.

#### The dataset used in this example comes from the How to Clean Excel Data tutorial from Breaking into Wall Street. The tutorial provides step by step instructions for how to clean the data using Excel functions. It is a very good tutorial. The example below shows how the same work can be completed using Python.

#### The advantages of Python in this case are:

    1) Speed of processing
    2) Replicability: It is easier to apply these transformations to another dataset using Python
    3) Readability: Python is easier to read and understand the various transformations applied to the data.
    4) Automation: The Python script could be executed automatically to clean the data without human intervention

In [1]:
! pip install openpyxl

Requirement already satisfied: openpyxl in /anaconda3/lib/python3.7/site-packages (2.6.2)
Requirement already satisfied: et-xmlfile in /anaconda3/lib/python3.7/site-packages (from openpyxl) (1.0.1)
Requirement already satisfied: jdcal in /anaconda3/lib/python3.7/site-packages (from openpyxl) (1.4.1)

In [2]:


import pandas as pd
import openpyxl 

filename = 'data/XL-02-PC-05-Cleaning-Up-Data-Before.xlsx'

wb = openpyxl.load_workbook(filename)
ws =  wb['Data']
df = pd.DataFrame(ws.values)

# Makes first line the column names
def make_header(df: pd.DataFrame)-> pd.DataFrame:
    df.columns = df.iloc[0]
    df.drop(df.index[0], inplace=True)
    return df

df = make_header(df)

# Expanding data in single columns to multiple columns
df[['First Name', 'Last Name']]= df['Customer Name'].str.split(" ", n=1, expand=True)
df[['Address', 'City', 'State', 'ZIP']]= df['Address, City, State, and ZIP'].str.split(",", n=3, expand=True)

# Changing the case of new columns
df['Address'] = df['Address'].str.title()
df['City'] = df['City'].str.title()
df['State'] = df['State'].str.upper()

In [3]:
df.head()

,Customer Name,Company Name,U.S. Telephone,"Address, City, State, and ZIP",Amount,Order Date,Sales Rep ID,First Name,Last Name,Address,City,State,ZIP
1,Jim van der Mheen,"Stokes, Rutherford and Bauch",+1 (728) 272-7491,"939 clear edge, mesita, wv, 14424",100003,2016-04-19 00:00:00,1,Jim,van der Mheen,939 Clear Edge,Mesita,WV,14424
2,Shenita Davenport,Waelchi Inc,+1 (267) 625-9210,"873 iron third harbor, whelen springs, nm, 37783",183593,2016-07-03 00:00:00,1,Shenita,Davenport,873 Iron Third Harbor,Whelen Springs,NM,37783
3,Jimmie Mcclure,"Braun, Crooks and Ortiz",+1 (837) 318-3929,"856 forge overpass, annandale, nm, 08463",159194,2016-10-21 00:00:00,1,Jimmie,Mcclure,856 Forge Overpass,Annandale,NM,08463
4,Marybelle Serrano,"Schamberger, Yost and Dach",+1 (885) 388-7212,"515 silver highlands, natalbany, wy, 00462",180394,2016-04-01 00:00:00,1,Marybelle,Serrano,515 Silver Highlands,Natalbany,WY,00462
5,Vito van Helpen,"Mann, Sauer and Sauer",+1 (350) 730-6802,"221 jagged harbor, franklin borough, ny, 80069",125979,2016-07-18 00:00:00,1,Vito,van Helpen,221 Jagged Harbor,Franklin Borough,NY,80069

In [4]:
from openpyxl.utils.dataframe import dataframe_to_rows

wb.create_sheet(index=0, title='Cleaned Data') # you may need to change this name if the example has already been done on the workbook
ws =  wb['Cleaned Data']

for r in dataframe_to_rows(df, index=False, header=True):
    ws.append(r)

wb.save(filename)
wb.close()



Resources:

    Openpyxl docs
    Automate the boring stuff